### ISSUE TITLE
Баг при добавлении адресной сущности либо образовательной организации.

### ISSUE THREAD

**Issue by emackovenko** [emackovenko/Rubin#2]
Если при вводе абитуриента добавлять новое образовательное учреждение, при сохранении самого заявления возникает ошибка валидации сущности на уровне EF. Сама ошибка еще не выявлена, так что надо выяснять

**Comment by Cepera97** [comment]
Пробовал добавить штук 5 новых заявлений в локальную базу, всем указал новое образовательное учреждение - сохранились без ошибки.

**Comment by emackovenko** [comment]
Так, щас освобожусь, попробую у себя поднять БД. Если что - отпишусь.
