### ISSUE TITLE
Реализовать удобный ввод результатов внутренних экзаменов

### ISSUE THREAD

**Issue by emackovenko** [emackovenko/Rubin#3]
Необходимо создать страницу, на которой будет выпадающий список предметов (комбобокс) и дата экзамена (датабокс), далее по кнопке выводить редактируемую таблицу (контрол на ваш выбор) с полями фио, первичный балл, основной балл. Во время редактирования при нажатии определенной кнопки (позже придумаю какой именно, пока пусть будет Enter) фокус ввода должен перемещаться на следующий контрол того же поля. Ну и в самом низу под таблицей кнопки "сохранить", "сброс". Если есть вопросы относительно того, как это реализовать - задавайте здесь, не стесняйтесь.

**Comment by prorab228** [comment]
Что такое первичный и основной балл, и где они хранятся?

**Comment by emackovenko** [comment]
Смотри: когда основные баллы вносят по одному, то получается, что у некоторых абитуриентов на сайте есть баллы, а у некоторых нет, ибо их еще не внесли. Поэтому вносят первичные (они не учитываются и не отображаются на сайте и в ФИСе), а потом, кога все готово, эти баллы переносятся в основные все разом.
